### ISSUE TITLE
Slower than Lunr JS

### ISSUE THREAD

**Issue by peterbe** [bvaughn/js-search#20]
I'm not sure how to phrase this. Just trying to reach out and share. 

I opened the jsperf links in the README and found Lunr JS a couple of percent faster actually. 

<img width="982" alt="screen shot 2017-01-25 at 9 55 44 am" src="https://cloud.githubusercontent.com/assets/26739/22295305/7ab70b68-e2e4-11e6-901d-d542e22ca637.png">

<img width="988" alt="screen shot 2017-01-25 at 9 56 06 am" src="https://cloud.githubusercontent.com/assets/26739/22295319/86b441ce-e2e4-11e6-9f85-697991b577ca.png">

`js-search` calls itself *"a lightweight implementation of Lunr JS, oferring runtime performance improvements"*. But it doesn't seem to be any runtime performance improvements. 

Or is it because Lunr JS has changed since you wrote the README?

**Comment by bvaughn** [comment]
Browsers change. Lunr has probably changed as well. js-search hasn't. I've spent more recent efforts on things like [js-worker-search](https://github.com/bvaughn/js-worker-search) which, altho less configurable, runs in a web worker and so can be faster.

I appreciate your taking the time to ask this question, but I'm going to close this issue since it's not really actionable. I'll edit the Gh description since it appears to no longer be accurate.

**Comment by bvaughn** [comment]
Hey @peterbe,

Your comment got me thinking so I recently spent some time polishing up benchmarks and doing a little performance tuning. Based on my benchmarks (which you can see [here](https://github.com/bvaughn/js-search/tree/master/benchmarks)<sup>1</sup>) js-search is **4 times faster** at building a search index than lunr (_32 ops/sec vs 8 ops/sec_). Unfortunately it is **26% slower** at running an individual search (_235k ops/sec vs 320k ops/sec_).

Take from this what you will. The most expensive part of search is creating an index. Both libraries are very fast at performing searches. I'd like to be faster at _both_ tasks but I could argue that the most important part to optimize is the index creation since it's several orders of magnitude slower.

<sup>1</sup> May be worth pointing out that the author of lunr adjusted these benchmarks (the lunr portion) after I created them so I'm confident they aren't misleading.

**Comment by peterbe** [comment]
It's late and I don't have the energy to dig deeper into the benchmark code, but one important thing I learned when I ended up using lunr in my app is that it does not store the "source". Searches gives back an array of "refs". In my case I ended up building something like this:

```javascript
this.searchIndex = elasticlunr(function () {
          this.addField('text')
          this.addField('notes')
          this.setRef('date')
          this.saveDocument(false)
        })
```
and searching, something like this:
```javascript
let found = this.searchIndex.search(
   text,
    searchConfig,
  )
 if (!found.length) {
   return Promise.resolve([])
 }
found.forEach(f => {
    // ... Here I look up the record from the IndexedDB by the "date" key. 
   // Actually, I look up with a big `date === found[0] || date === found[1] || ...`
})
```

`js-search` returns the "source" when you search. That can be quite useful and saves that extra step converting the "primary key" into its original source object.

**Comment by peterbe** [comment]
By the way, I chose lunr in my app because I can incrementally add documents to the index. I think `js-search` only has `addDocuments()`, whereas with `lunr` I can do things like:
```jsx
<form onSubmit={e => {
  this.db.saveThing(this.state.id, this.refs.myinput.value)
  this.lunrSearchIndex.addDoc({id: this.state.id, 'value': this.refs.myinput.value})
}}>
```

**Comment by peterbe** [comment]
Oh. And the fact that with lunr I can search on different fields depending on the need. 
The alternative solution to this would be something like:
```javascript
var searchTitles = new JsSearch.Search('isbn');
searchTitles.addIndex('title');
searchTitles.addDocuments([theGreatGatsby, theDaVinciCode, angelsAndDemons]);
var searchNotes = new JsSearch.Search('isbn');
searchNotes.addIndex('title');
searchNotes.addDocuments([theGreatGatsby, theDaVinciCode, angelsAndDemons]);
```

**Comment by bvaughn** [comment]
js-search also supports incrementally adding documents. Searching on
particular fields is not supported but I suppose could be added without too
much difficulty.

Anyway, this is _not_ me trying to convince you to use js-search. I just
wanted to clarify performance.
