### ISSUE TITLE
Punctuation and special characters seems to cause issues

### ISSUE THREAD

**Issue by ashnayde** [bvaughn/js-search#26]
Using the default strategy, this is what I have:

    function searchGrid(columns, rows, searchQuery) {
        const searcher = new JSSearch.Search('rowId');

        columns.forEach((key) => {
          searcher.addIndex(key);
        });

        searcher.addDocuments(rows);

        return searcher.search(searchQuery);
    }

When I enter a decimal point or a slash (for dates), I'm getting back no search results, even though I have decimal and date values in my data.

**Comment by bvaughn** [comment]
Share a repro case please 😄

**Comment by ashnayde** [comment]
Sorry, not quite following. Do you need a sample of the data in question?

**Comment by bvaughn** [comment]
Yes. Something I can run and see the error you're reporting.

**Comment by ashnayde** [comment]
Here you go: https://jsfiddle.net/8kL4f45q/1/

The first 3 results are expected. The next two (slash and period), yield no results as I mentioned in the issue stated above. The last case (full date) also yields an unexpected result that I noticed while putting the fiddle together - getting 3 rows instead of 1 as I would expect.

**Comment by bvaughn** [comment]
I see. Thank you for the fiddle.

The reason the 3rd and 4th search returns no results is because of tokenization. By default, js-search uses [`SimpleTokenizer`](https://github.com/bvaughn/js-search/blob/master/source/Tokenizer/SimpleTokenizer.js) which strips all non-alpha-numeric characters (eg punctuation, slashes). This means that searches containing _only_ those characters will match no documents.

You can provide your own tokenizer if you want your searches to be punctuation-sensitive. A simple implementation you start with would be:
```js
searcher.tokenizer = {
  tokenize: (text) => text.split(/[\s]+/)
};
```

Your search examples also suggest that you want all possible substring matches (eg "at" matches "cat" and "bat"). By default js-search uses prefix matching. You can change this to use another built-in strategy:
```js
searcher.indexStrategy = new JsSearch.AllSubstringsIndexStrategy();
```

At this point, your search should yield the results you expect. 😄
