### ISSUE TITLE
Comparison with lunr.js

### ISSUE THREAD

**Issue by meltuhamy** [bvaughn/js-search#29]
Hello,

It would be nice to have a better comparison with lunr.js. I was under the impression that this library is smaller and faster, but running the jsperf shows it is slower...  http://jsperf.com/js-search-vs-lunr-js-running-searches/5 

Thanks!

**Comment by bvaughn** [comment]
The benchmark you linked to is from August 2015. Browsers change. Lunr has probably changed since then as well. I've spent more recent efforts on things like [js-worker-search](https://github.com/bvaughn/js-worker-search) which, altho less configurable, runs in a web worker and so can be faster.

However I did spend some time recently polishing up benchmarks and doing a little performance tuning. Based on my benchmarks (which you can see [here](https://github.com/bvaughn/js-search/tree/master/benchmarks)<sup>1</sup>) js-search is **4 times faster** at building a search index than lunr (_32 ops/sec vs 8 ops/sec_). Unfortunately it is **26% slower** at running an individual search (_235k ops/sec vs 320k ops/sec_).

Take from this what you will. The most expensive part of search is creating an index. Both libraries are very fast at performing searches. I'd like to be faster at _both_ tasks but I could argue that the most important part to optimize is the index creation since it's several orders of magnitude slower.

This isn't really an actionable issue, so I'm closing it.

<sup>1</sup> May be worth pointing out that the author of lunr adjusted these benchmarks (the lunr portion) after I created them so I'm confident they aren't misrepresentating the library.
