### ISSUE TITLE
Support nordic characters

### ISSUE THREAD

**Issue by guoyunhe** [bvaughn/js-search#36]
In one of my project <http://shrgrp.org>, the names of objects may contain some Finnish characters, like:
```
hyväntoivonkatu 6
```

On English keyboard, it is hard to type "ä" and I hope I can search it by typing "hyvantoivonkatu". Is it supported by js-search?

**Comment by bvaughn** [comment]
No, this isn't supported by default. You would need to implement your own [`IndexStrategy`](https://github.com/bvaughn/js-search/blob/master/source/IndexStrategy/IndexStrategy.js) that mapped characters like "ä" to their more easily-typed variants (eg "a").

I don't have plans to implement this myself. If you write it in such a way as to be reusable for others though I would be happy to review a PR for consideration to be added into js-search 😄  Otherwise you can pass in your own implementation:

```js
const search = new JsSearch.Search('isbn');
search.indexStrategy = YourIndexStrategy;
```
