### ISSUE TITLE
Division by zero in dist/umd/js-search.min.js

### ISSUE THREAD

**Issue by vladimirramik** [bvaughn/js-search#45]
Great libraries Mr Vaughn. Very happy to be using your react virtualized in many things.

Our code scan popped up a division by zero in js-search:
`l===1/0&&(l=0);`

**Comment by bvaughn** [comment]
Hey @vladimirramik 😄  Thanks!

This is actually intentional. The [code in question](https://github.com/bvaughn/js-search/blob/2e20252b10504fb69001375d6833cacd14e936fa/source/SearchIndex/TfIdfSearchIndex.js#L151) uses `Infinity` but that gets converted to `1 / 0` during bundling.

Since `Infinity` is a specific case I check for, I don't think there's any cause for concern here.
