### ISSUE TITLE
Search only specific fields?

### ISSUE THREAD

**Issue by Knacktus** [bvaughn/js-search#49]
Is it possible to specify a field / some fields when searching? In the overview example:

```
// tags is the name of the field
search(["tags"], "book")
```

Cheers and best regards,

Jan

P.S.: I still can't believe the indexing speed. :-)

**Comment by bvaughn** [comment]
Unfortunately that feature is not supported. All indexed fields feed into the same search index. You would need to either:

1. construct multiple indexes, one per field you wanted to be able to search uniquely, or
1. do a second search pass over results to filter out ones that don't contain the search string in the specific field you wanted to search (which would potentially be slow)

Going to close this issue since it's just a question and the question has been answered.

> P.S.: I still can't believe the indexing speed. :-)

Thanks 😁
