### ISSUE TITLE
Searching for special characters

### ISSUE THREAD

**Issue by broadhu2** [bvaughn/js-search#50]
Is there a setting that allows searching using special characters like '$', '@', '#', etc.? 

I am using react-select-fast-filter-options but I think my question is more related to its underlying use of js-search. I have a long list of DB2 schemas as my dropdown options, some of which are named things like "$$@", which were created in test environments but are valid options. 

Normal alphanumeric characters work fine when I search for schemas, but when I type to search for options with only special characters, I get no results (even though I can see the schemas with special characters when I scroll through the list).

**Comment by bvaughn** [comment]
This is because the default tokenizer ([`SimpleTokenizer`](https://github.com/bvaughn/js-search/blob/master/source/Tokenizer/SimpleTokenizer.js)) splits words on non-alpha-numeric characters.

You can accomplish what you're aiming for by implementing your own tokenizer. It's really straight forward!

```js
class CustomTokenizer {
  tokenize(text) {
    return text
      .split(/\s+/)    // eg Split on whitespace
      .filter(
        (text) => text // Filter empty tokens
      );
  }
};

var search = new Search('id');
search.tokenizer = new CustomTokenizer();
// ...
```
