### ISSUE TITLE
Prebuild index, serialize and restore! Is this possible?

### ISSUE THREAD

**Issue by kozi** [bvaughn/js-search#55]
Prebuild index, serialize and restore! Is this possible?

**Comment by bvaughn** [comment]
Not currently supported.

I've experimented with this briefly and did not find any big performance wins. As I mentioned in issue #16, I think the larger perceived perf win would be to move the search index into a web worker, which I've done with another project of mine: https://github.com/bvaughn/js-worker-search

You would be welcome to implement serialization and loading in this library and submit a PR if you'd like. If it performs well, I would be happy to merge it. But I don't plan to implement this myself. 😄

**Comment by kozi** [comment]
The WebWorker is not persistent on a page reload, so the webworker must Build the Index after every page reload. Or am i wring?

**Comment by bvaughn** [comment]
That's correct, but the perceived cost of rebuilding is _much_ less if the index is built in a worker.

**Comment by kozi** [comment]
Is there a chance to get the code you have experimented with?
In my test case i got an array of entries (7MB as JJSON-String) and the IE11 took over 10 seconds to build the index (in a webworker).

**Comment by bvaughn** [comment]
No, sorry. I don't think I have that laptop anymore.

**Comment by tskarman** [comment]
there is some such work on your branch serialize-and-restore of this repo. i don’t know, if that’s what you are looking for.

i think at least one of the strategies serialized the entire object graph. which means that the resulting json would become large and repetitive and suffer with large documents. so there are some low-hanging fruits to be had.
but i didnt go down that path, because in the end, first-time cost seemed more important.

but serialization becomes interesting once again if you consider supplying the index pre-built from the server.

**Comment by bvaughn** [comment]
I had done some more recent work writing/parsing a really compact format.

I'll see if I can dig it up later.

Sorry! I have a lot going on right now and this isn't super high priority for me.
